apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-cm
spec:
  containers:
  - image: ramane/fortune:env              # using fortune image taged with env to generate html files
    env:
    - name: INTERVAL                       # adding a single variable to the environement variable to list
      valueFrom:                           # instead of setting the ENV w'll get its value form ConfigMap
        configMapKeyRef:
          name: fortune-config             # name of the configMap
          key: sleep-interval              # the key of the needed ENV       
    name: html-generator
    volumeMounts:
      - name: html                         # using volume by its name, mounted at var/htdocs
        mountPath: /var/htdocs
  - image: nginx:alpine                    # using nginx image from docker hub as a server to serve html files
    name: web-server
    volumeMounts:
      - name: html                         # using volume by its name in readOnly to serve a generated html files
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:                                 # defining a volume type emptyDir with name:html
    - name: html
      emptyDir: {}

# apiVersion: v1
# kind: Pod
# metadata:
#  name: fortune-args-from-configmap
# spec:
#   containers:
#   - image: luksa/fortune:args      using the image that takes the interval from the first argument , not from an environment variable
#     env:                           defining the environment variable exactly as before
#     - name: INTERVAL
#       valueFrom:
#         configMapKeyRef:
#           name: fortune-config
#           key: sleep-interval
#     args: ["$(INTERVAL)"]           Referencing the environment variable in the argument   
# ...


