apiVersion: batch/v1
kind: Job
metadata:
  name: mutli-completion
spec:
  completions: 3     # nomber of job must run
  parallelism: 2     # 2 jobs can run in parallel
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job


# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: mutli-completion
# spec:
#   completions: 3     # nomber of job must run sequentially not in parallel
#   template:
#     metadata:
#       labels:
#         app: batch-job
#     spec:
#       restartPolicy: OnFailure
#       containers:
#       - name: main
#         image: luksa/batch-job
# to scale job kubectl scale job multi-completion-batch-job --replicas 3 will change parallelism property