apiVersion: v1                   # this manifest is decoupled from infra, and it can reused
kind: PersistentVolumeClaim   
metadata:
 name: mongodb-pvc-2
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: fast