apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd    # this provisionner use gce (GOOGLE COMPUTE ENGINE) Persistent Disk (PD) specific to GKE
parameters:
  type: pd-ssd
  zone: europe-west4-a